name: "Cron агенты"
description: "Выполнение произвольных методов по расписанию"
settings_params:
  - {
      variable: enabled,
      name: "Включено",
      options: [{ name: "Нет", value: 0 }, { name: "Да", value: 1 }],
    }
menu_section: addon
version: 1.1
